/// <reference types="cypress" />

describe('Test Case 1', () => {
  it('Test Case 1', () => {
    cy.visit('https://automationexercise.com')
    cy.url().should('eq', 'https://automationexercise.com/')
    cy.get('a').contains('Home').should('have.css', 'color', 'rgb(255, 165, 0)')
    cy.get('li').contains('Signup').click()
    cy.get('h2').should('contain', 'New User Signup!')
    cy.get('[data-qa="signup-name"]').type('mahefa')
    cy.get('[data-qa="signup-email"]').type('mahefa@gmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('.title').should('contain', 'Enter Account Information')
    cy.get('input[name="title"][value="Mr"]').check()
    cy.get('#password').type('123456')
    cy.get('#first_name').type('Randria')
    cy.get('#last_name').type('Mahefa')
    cy.get('#company').type('Independant Inc.')
    cy.get('#address1').type('Iavoloha')
    cy.get('#address2').type('Mahazo')
    cy.get('#country').select('India')
    cy.get('#state').type('Mumbay')
    cy.get('#city').type('Mumbay')
    cy.get('#zipcode').type('101')
    cy.get('#mobile_number').type('0320714589')
    cy.get('[data-qa="create-account"]').click()
    cy.get('[data-qa="account-created"]').should('contain', 'Account Created!')
    cy.get('[data-qa="continue-button"]').click()
    cy.get('.navbar-nav').should('contain', 'Logged in as mahefa')
    cy.get('li').contains('Delete Account').click()
    cy.get('[data-qa="account-deleted"]').should('contain', 'Account Deleted!')
    cy.get('[data-qa="continue-button"]').click()
  })
})
